### ISSUE TITLE
ValueError: the input array must have size 3 along `channel_axis`

### ISSUE THREAD

**Issue by csmiguel** [TankredO/traitor#1]
Thanks for this software. I am encountering this issue when scanning some seeds. The sample images work great so I guess it must be an issue related to the color of this particular image.
![len](https://github.com/TankredO/traitor/assets/12279367/1fcfd539-b2bc-402d-ad3c-5860b4cffb02)

```
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/traitor/cli/extract.py", line 153, in single_wrapped
    run_single(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/traitor/cli/extract.py", line 77, in run_single
    bin_image = segment_image2(image, bg_col=bg_col, k=2)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/traitor/tools.py", line 63, in segment_image2
    image = skimage.color.rgb2lab(image)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/skimage/_shared/utils.py", line 394, in fixed_func
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/skimage/color/colorconv.py", line 1139, in rgb2lab
    return xyz2lab(rgb2xyz(rgb), illuminant, observer)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/skimage/_shared/utils.py", line 394, in fixed_func
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/skimage/color/colorconv.py", line 746, in rgb2xyz
    arr = _prepare_colorarray(rgb, channel_axis=-1).copy()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/skimage/color/colorconv.py", line 140, in _prepare_colorarray
    raise ValueError(msg)
ValueError: the input array must have size 3 along `channel_axis`, got (819, 1117, 4)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/traitor", line 8, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/traitor/cli/extract.py", line 300, in extract
    list(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
ValueError: the input array must have size 3 along `channel_axis`, got (819, 1117, 4)
```

Thanks

**Comment by TankredO** [comment]
Hi Miguel,

thanks for opening this issue.

The issue seemed to be that the image you supplied contained an alpha channel, i.e., transparency, in addition to the three color channels. I pushed a new version of the package, where the alpha channel is ignored.

Please let me know whether it's working now :)

**Comment by csmiguel** [comment]
Thanks! problem solved. However, I now have trouble installing `traitor` using `pip install git+https://github.com/TankredO/traitor`. Instead, I had to download the repo in a zip file and install it from local `pip  install traitor-main.zip`.
